// Individual prop firm review data

export const firmReviews = [
  {
    slug: "topstep",
    name: "TopStep",
    founded: "2012",
    hq: "Chicago, IL",
    url: "https://www.topstep.com",
    color: "#3B82F6",
    tagline: "The original futures prop firm. Strictest rules, strongest reputation, best education ecosystem.",
    tldr: "TopStep is the most established futures prop firm, operating since 2012 out of Chicago. A 1-step Trading Combine evaluation with end-of-day drawdown, 100% of your first $10K in profits, and an exclusive platform (TopstepX). Monthly subscription pricing at $49-$149. Best for beginners who value structure and education.",
    overview: [
      { id: "what-is-topstep", heading: "What is TopStep?", body: "TopStep is a proprietary trading firm founded in 2012 by Michael Patak in Chicago. It was the first company to offer retail traders a structured path to trading futures with firm capital through a simulated evaluation. Before TopStep, getting access to prop firm capital required physical presence on a trading desk, personal connections, or significant personal capital.\n\nThe firm focuses exclusively on futures trading and has funded thousands of traders since launch. They've paid out millions in trader profits and remain the most recognized name in the futures prop firm space. The company rebranded from TopstepTrader to TopStep in 2020 and shifted from a 2-step to a 1-step evaluation in 2023." },
      { id: "how-eval-works", heading: "How the evaluation works", body: "TopStep uses a single-phase evaluation called the Trading Combine. You pick an account size ($50K, $100K, or $150K), pay a monthly subscription, and trade in a simulated environment. Your goal is to hit the profit target without exceeding the Maximum Loss Limit (MLL).\n\nThe MLL is a trailing drawdown calculated at end of day, not intraday. This is a critical distinction. If you're down $1,800 during the session but fight back to positive before 4:00 PM CT, the drawdown is based on your closing balance, not the intraday low. This gives traders room to manage positions through normal volatility.\n\nThere is no minimum number of trading days to pass the evaluation. You could theoretically pass in a single day if you hit the profit target. Once you pass, you pay a $149 activation fee and transition to a funded account." },
      { id: "account-types", heading: "Account sizes and pricing", body: "TopStep offers three account sizes, all on monthly subscription pricing:\n\nThe $50K account costs $49 per month with a $3,000 profit target (6%) and a $2,000 Maximum Loss Limit. Maximum position size is 5 contracts.\n\nThe $100K account costs $99 per month with a $6,000 profit target (6%) and a $3,000 MLL. Maximum position size is 10 contracts.\n\nThe $150K account costs $149 per month with a $9,000 profit target (6%) and a $4,500 MLL. Maximum position size is 15 contracts.\n\nAll accounts include Level 1 market data and CME exchange data at no additional cost. Level 2 (DOM) data is available as an upgrade. TopStep covers the monthly data fee for one exchange (CME by default)." },
      { id: "fine-print", heading: "The fine print", body: "TopStep's rule set is relatively simple compared to competitors, but there are important details.\n\nThe MLL is a trailing drawdown. It follows your highest end-of-day balance upward but never moves back down. If your account peaks at $53,000 (starting from $50,000), your MLL is now calculated from that $53,000 high-water mark.\n\nThere is no consistency rule during the evaluation. You can have one massive winning day and several flat days, and that's acceptable. Some firms penalize this pattern.\n\nAs of July 2025, TopstepX is the only supported trading platform. The firm acquired the ProjectX technology and no longer supports NinjaTrader, TradingView, Tradovate, or other third-party platforms. This is a significant limitation if you have a workflow built around other software.\n\nAll positions must be closed by market close. No overnight or weekend holding is allowed in either the evaluation or funded phases.\n\nResets are available if you fail: $49 for the $50K, $99 for $100K, and $149 for $150K. A free reset is included with monthly subscription renewal if your account is in failed status." },
      { id: "payout-structure", heading: "Payout structure", body: "TopStep's payout structure has evolved over time. Currently, traders keep 100% of their first $10,000 in profits with no split. After $10,000, the split moves to 90/10 in favor of the trader.\n\nPayouts can be requested daily after meeting minimum requirements. Initially, traders must have 30 winning days before daily payout eligibility. In the early funded phase, there are payout caps that increase as you demonstrate consistency.\n\nTopStep uses a Scaling Plan that progressively increases your buying power as your end-of-day balance grows. You don't start with the full contract allocation. The scaling is tied to your account equity, encouraging measured growth rather than maximum leverage from day one.\n\nYou can run up to 5 funded accounts simultaneously. Each account operates independently with its own drawdown and profit tracking." },
    ],
    verdict: "TopStep is the safest choice for a first prop firm evaluation. The end-of-day drawdown is genuinely more forgiving than intraday trailing. The education ecosystem (TopstepTV, coaching, community) adds real value that competitors don't match. The tradeoff is the monthly subscription model (costs add up if you don't pass quickly), the $149 activation fee, and being locked into TopstepX as your only platform. If you're already committed to a specific trading platform like NinjaTrader or TradingView, this is a dealbreaker.",
    bestFor: "Beginners and traders who value education, community, and a proven track record above everything else.",
    avoidIf: "You need NinjaTrader, TradingView, or any platform other than TopstepX. Or if you prefer one-time pricing over monthly subscriptions.",
    relatedTerms: [
      { term: "Drawdown", slug: "drawdown" },
      { term: "Position Sizing", slug: "position-sizing" },
      { term: "Prop Firm / Funded Account", slug: "prop-firm" },
      { term: "Day Trade Margin", slug: "day-trade-margin" },
    ],
    specs: [
      { label: "Account", values: ["$50K", "$100K", "$150K"] },
      { label: "Monthly cost", values: ["$49", "$99", "$149"] },
      { label: "Profit target", values: ["$3,000", "$6,000", "$9,000"] },
      { label: "Max loss limit", values: ["$2,000", "$3,000", "$4,500"] },
      { label: "Max contracts", values: ["5", "10", "15"] },
      { label: "Activation fee", values: ["$149", "$149", "$149"] },
    ],
    pros: [
      "Longest operating history in the industry (since 2012)",
      "End-of-day drawdown is the most forgiving calculation method",
      "No consistency rule during evaluation",
      "100% of first $10K in profits",
      "Best education resources of any prop firm (TopstepTV, live coaching)",
      "Free reset included with monthly subscription renewal",
    ],
    cons: [
      "Monthly subscription pricing adds up if you need multiple attempts",
      "$149 activation fee after passing evaluation",
      "TopstepX is the only platform option since late 2025",
      "Trustpilot rating has declined (3.4) amid platform and rule changes",
      "Scaling Plan limits initial contract size in funded accounts",
      "No overnight or swing trading at any phase",
    ],
  },
  {
    slug: "apex",
    name: "Apex Trader Funding",
    founded: "2021",
    hq: "Austin, TX",
    url: "https://www.apextraderfunding.com",
    color: "#EF9F27",
    tagline: "The biggest scale play in futures prop trading. Maximum capital, maximum accounts, maximum complexity.",
    tldr: "Apex Trader Funding is the largest futures prop firm by volume, with the widest range of account sizes ($25K-$300K) and up to 20 simultaneous accounts. 100% of your first $25K in profits. Underwent a major rules overhaul in March 2026. Frequent 50-80% off sales make evaluations very affordable, but the funded rules have become more complex.",
    overview: [
      { id: "what-is-apex", heading: "What is Apex Trader Funding?", body: "Apex Trader Funding was founded in 2021 by Darrell Martin in Austin, Texas. It has grown into one of the most searched and highest-traffic prop firms in the world, with over 4 million monthly website visitors and reported payouts exceeding $700 million.\n\nApex built its early reputation on simple rules and aggressive promotions. Sales of 50-80% off are common and widely promoted through affiliate channels and social media. At these discounted prices, a $50K evaluation can cost as little as $35 per month, making it one of the cheapest ways to attempt a prop firm evaluation.\n\nHowever, Apex has undergone significant changes, particularly a major rules overhaul in March 2026 that redesigned how funded accounts work." },
      { id: "how-eval-works", heading: "How the evaluation works", body: "Apex uses a one-step evaluation. You purchase an account, hit the profit target, and transition to a Performance Account (PA). The minimum trading days requirement is just 1 day during the evaluation phase.\n\nThe evaluation has no consistency rule, which means you can pass with a single large winning day. This is one of the most permissive evaluation structures in the industry.\n\nAs of March 2026, Apex uses hard-stop enforcement through Rithmic and Tradovate. The platform automatically rejects any order that doesn't include a bracket (stop loss and take profit). This is a mandatory rule, not optional. While it prevents accidental drawdown violations, it also limits discretionary traders who manage exits manually.\n\nApex offers both end-of-day (EOD) and intraday trailing drawdown options. The EOD trail is more forgiving. The intraday trail adjusts in real time as your equity reaches new highs during the session. Choose carefully, because this affects your probability of survival significantly." },
      { id: "account-types", heading: "Account sizes and pricing", body: "Apex offers five account sizes: $25K, $50K, $100K, $150K, and $300K. Monthly evaluation costs range from $147 to $517 at full price.\n\nHowever, almost nobody pays full price. Apex runs frequent promotions (50-80% off) that are essentially the real pricing. A $50K evaluation during an 80% off sale costs approximately $35 per month. If you're considering Apex, wait for a sale. They happen regularly.\n\nThe March 2026 update began transitioning from monthly subscriptions to one-time fee models on some account types. Check the current pricing structure directly on their site, as this transition is still in progress.\n\nProfit targets range from $1,500 on the $25K account to $20,000 on the $300K account. Drawdown thresholds vary by account size." },
      { id: "fine-print", heading: "The fine print", body: "Apex's rule set became significantly more complex after the March 2026 overhaul. Here are the details that matter most.\n\nThe 50% consistency rule on funded accounts requires that no single trading day accounts for more than 50% of your total profit at payout time. This replaced the previous 30% rule and is more lenient, but still requires spreading your profits across multiple days.\n\nMandatory bracket orders on all trades since March 2026. Every entry must include a stop loss and take profit. The platform will reject orders without brackets.\n\nAutomated contract scaling enforced by the platform. You cannot exceed the position limit for your account tier. The system physically prevents it rather than flagging it after the fact.\n\nPayout structure uses tiered caps for the first 6 payouts. The maximum you can withdraw increases with each payout cycle. After 6 payouts, the account is closed under the new model. This is a significant change from the previous structure.\n\nNo overnight holding. All positions must be closed by 4:59 PM ET.\n\nThe 30% negative P&L rule: your open trades cannot exceed 30% of your start-of-day profit in unrealized losses." },
      { id: "payout-structure", heading: "Payout structure", body: "Apex's biggest selling point is the profit split: 100% of your first $25,000 in profits with no split. After that, the split is 90/10 in favor of the trader. This is the highest initial retention in the industry.\n\nPayout eligibility begins after 8 trading days with at least 5 days showing $50 or more in profit. Payouts are processed through Deel and traders can request up to 2 withdrawals per month.\n\nThe new model (March 2026) introduces tiered payout caps for the first 6 withdrawals. The amount you can withdraw per request increases as you progress through the tiers. After 6 total payouts, the funded account is closed.\n\nThis structure is designed to reward consistent, sustained profitability rather than large one-time withdrawals. However, the 6-payout closure is a hard limit that some traders find restrictive.\n\nYou can run up to 20 funded accounts simultaneously, which is the highest in the industry. This allows aggressive scaling for traders with proven strategies." },
    ],
    verdict: "Apex offers the most capital and the best profit retention (100% of first $25K), but the March 2026 rule changes added genuine complexity. The mandatory bracket orders, 6-payout account closure, and tiered withdrawal caps mean you need to plan your payout strategy carefully. The frequent sales make evaluations very cheap, which is a real advantage. Best suited for experienced traders who can navigate the rules and want maximum scale potential through multiple accounts.",
    bestFor: "Experienced traders who want maximum capital access, platform choice, and can handle a complex rule set. Traders who want to run many accounts simultaneously.",
    avoidIf: "You're new to prop firms and want simple rules. Or if the mandatory bracket order requirement conflicts with how you manage trades.",
    relatedTerms: [
      { term: "Drawdown", slug: "drawdown" },
      { term: "Bracket Order", slug: "bracket-order" },
      { term: "Position Sizing", slug: "position-sizing" },
      { term: "Risk-Reward Ratio", slug: "risk-reward-ratio" },
    ],
    specs: [
      { label: "Account", values: ["$25K", "$50K", "$100K", "$150K", "$300K"] },
      { label: "Monthly cost", values: ["$147", "$167", "$207", "$297", "$517"] },
      { label: "With 80% sale", values: ["~$29", "~$33", "~$41", "~$59", "~$103"] },
      { label: "Profit target", values: ["$1,500", "$3,000", "$6,000", "$9,000", "$20,000"] },
      { label: "Max contracts", values: ["4", "10", "14", "17", "25"] },
    ],
    pros: [
      "100% of first $25K in profits (highest retention in industry)",
      "Up to 20 simultaneous accounts for maximum scaling",
      "Widest platform selection (Rithmic, Tradovate, NinjaTrader, TradingView, WealthCharts)",
      "Frequent 50-80% sales make evaluations extremely affordable",
      "Largest account sizes available (up to $300K)",
      "No consistency rule during evaluation phase",
    ],
    cons: [
      "March 2026 overhaul added complexity (mandatory brackets, tiered payouts, 6-payout closure)",
      "Full-price evaluations are expensive without a sale",
      "Intraday trailing drawdown option is punishing for most traders",
      "Trustpilot rating dropped amid frequent rule changes",
      "The 30% negative P&L rule on open trades adds another constraint",
      "Account closes after 6 payouts under the new model",
    ],
  },
  {
    slug: "tradeify",
    name: "Tradeify",
    founded: "2022",
    hq: "Boca Raton, FL",
    url: "https://tradeify.co",
    color: "#5DCAA5",
    tagline: "The most flexible futures prop firm. Choose your funded path after you pass.",
    tldr: "Tradeify offers three account families (Select, Growth, Lightning) with one-time pricing and $0 activation fees. The standout feature: Select lets you pass one evaluation and then choose between two different funded paths. EOD drawdown on all accounts. 90/10 profit split. Path to Elite Live (real capital) after 5 payouts.",
    overview: [
      { id: "what-is-tradeify", heading: "What is Tradeify?", body: "Tradeify is a futures prop firm founded in 2022 by Brett Simba in Boca Raton, Florida. Despite being newer than TopStep and Apex, Tradeify has built a strong reputation quickly, earning a 4.8 rating on Trustpilot from over 1,600 reviews.\n\nThe firm went through a major product overhaul (version 3.0) that restructured its offerings into three distinct account families: Select, Growth, and Lightning. All plans now use one-time pricing with no monthly subscriptions, which is a significant departure from the industry norm.\n\nTradeify's core innovation is the Select plan, which lets traders pass a single evaluation and then choose between two different funded account structures depending on their trading style and payout preferences." },
      { id: "how-eval-works", heading: "How the evaluations work", body: "Tradeify offers two evaluation paths and one instant-funded option.\n\nSelect is a 3-day minimum evaluation with a 40% consistency rule (your best day cannot exceed 40% of total profits). After passing, you choose between Flex (5-day payout cycles, no daily loss limit, no funded consistency rule) or Daily (daily payout eligibility, but with a daily loss limit and buffer requirements). This choose-after-passing structure is unique in the industry.\n\nGrowth is a 1-day minimum evaluation with no consistency rule during the eval phase. The funded account has a 35% consistency rule and a daily loss limit. Growth is cheaper than Select but has more restrictions once funded.\n\nLightning is instant funded with no evaluation. You pay a higher one-time fee and start trading for payouts immediately. Rules are stricter with a progressive consistency rule (20%, increasing to 25% after first payout, 30% after second).\n\nAll three use end-of-day trailing drawdown that locks once your balance exceeds the starting capital plus the drawdown amount plus $100." },
      { id: "account-types", heading: "Account sizes and pricing", body: "All pricing is one-time (no recurring subscriptions).\n\nSelect evaluations: $159 for $50K, $259 for $100K, $359 for $150K. Discount codes commonly reduce these by 30-50%.\n\nGrowth evaluations: approximately $97 for $50K. Generally the cheapest evaluation option.\n\nLightning (instant funded): $244-$510 one-time depending on account size. No evaluation required.\n\nA $25K account is also available as the cheapest entry point.\n\nAll accounts have $0 activation fees. This is a real differentiator. After passing a TopStep evaluation you pay $149 to activate. At Tradeify, you pay nothing." },
      { id: "fine-print", heading: "The fine print", body: "Tradeify's rule set varies significantly across account families, which is both a strength (flexibility) and a weakness (complexity).\n\nSelect Flex is the most trader-friendly funded structure available: no daily loss limit, no funded consistency rule, EOD drawdown. Your best day can be 90% of your total profit without penalty.\n\nSelect Daily has a daily loss limit, buffer requirements, and profit targets between each payout. This path has substantially more rules than Flex.\n\nMicro-scalping rule on all accounts: 50%+ of your trades must be held longer than 10 seconds AND 50%+ of your profit must come from trades held longer than 10 seconds. This prevents pure HFT strategies.\n\nNo overnight holding on any account type until you reach Elite Live status.\n\nAll positions must be closed by 4:59 PM ET.\n\nCopy trading is only allowed between your own Tradeify accounts, not from external signal services.\n\nAfter 5 total payouts across any combination of accounts, you become eligible for Tradeify Elite, which is real capital trading on live CME exchanges. This is not automatic. Tradeify reaches out when you qualify." },
      { id: "payout-structure", heading: "Payout structure", body: "The profit split is 90/10 in favor of the trader on most account types. Some Growth accounts operate at 80/20 unless upgraded.\n\nSelect Flex payouts are available every 5 days. Select Daily payouts are available daily. The minimum payout amount is $1,000.\n\nPayout processing is fast: 24-48 hours on funded accounts, reportedly as fast as 1 hour on live accounts.\n\nPayout caps vary by account type and payout number. Caps generally increase with each successive payout cycle.\n\nThe path to Elite Live is a genuine differentiator. After 5 payouts, you trade real capital on CME exchanges instead of a simulation. However, the transition is at Tradeify's discretion, not automatic." },
    ],
    verdict: "Tradeify is the most flexible futures prop firm available. The Select Flex path (no funded consistency, no DLL, $0 activation) is genuinely the most permissive funded structure in the industry. The one-time pricing model means no bleeding subscription fees while you practice. The tradeoff is complexity across three account families and a shorter track record than TopStep. If you can navigate the options and pick the right plan for your style, the value proposition is strong.",
    bestFor: "Traders who want to evaluate once and choose their funded structure afterward. Anyone who hates monthly subscriptions and activation fees.",
    avoidIf: "You find the three account families confusing, or you want the simplest possible rule set with zero decisions to make.",
    relatedTerms: [
      { term: "Drawdown", slug: "drawdown" },
      { term: "Prop Firm / Funded Account", slug: "prop-firm" },
      { term: "Scalping", slug: "scalping" },
      { term: "Risk-Reward Ratio", slug: "risk-reward-ratio" },
    ],
    specs: [
      { label: "Plan", values: ["Select $50K", "Select $100K", "Select $150K", "Growth $50K", "Lightning $50K"] },
      { label: "Cost (one-time)", values: ["$159", "$259", "$359", "~$97", "$244"] },
      { label: "Min. days", values: ["3", "3", "3", "1", "0 (instant)"] },
      { label: "Profit target", values: ["$3,000", "$6,000", "$9,000", "$3,000", "N/A"] },
      { label: "Activation fee", values: ["$0", "$0", "$0", "$0", "$0"] },
    ],
    pros: [
      "$0 activation fee on all account types",
      "One-time pricing, no monthly subscriptions",
      "Select Flex: no daily loss limit, no funded consistency rule",
      "Choose your funded path (Flex or Daily) after passing evaluation",
      "EOD drawdown that locks once you build a buffer",
      "Path to Elite Live (real capital) after 5 payouts",
      "4.8 Trustpilot rating from 1,600+ reviews",
    ],
    cons: [
      "Three account families create decision paralysis for new traders",
      "Select Daily funded path has many more restrictions than Flex",
      "80/20 split on some Growth accounts unless upgraded",
      "Micro-scalping rule (10-second minimum) may affect some strategies",
      "Shorter operating history than TopStep (founded 2022)",
      "Elite Live transition is discretionary, not guaranteed",
    ],
  },
  {
    slug: "lucid",
    name: "Lucid Trading",
    founded: "2025",
    hq: "United States",
    url: "https://lucidtrading.com",
    color: "#AFA9EC",
    tagline: "The newest entrant with the cleanest rule set and the fastest payouts in the industry.",
    tldr: "Lucid Trading launched in 2025 and has quickly gained traction with one-time pricing, EOD drawdown, and the most permissive funded rules in the industry (LucidFlex: no DLL, no funded consistency). Average payout processing is 15 minutes. Multiple account types (Flex, Pro, Direct, Maxx) for different trading styles. The tradeoff is a very short track record.",
    overview: [
      { id: "what-is-lucid", heading: "What is Lucid Trading?", body: "Lucid Trading is a futures prop firm founded by AJ Campanella in early 2025. It's the newest of the major firms and has grown quickly by addressing specific pain points traders had with established competitors: subscription fatigue, slow payouts, complex rules, and funded consistency requirements.\n\nThe firm has served over 14,000 traders and paid out over $10 million since launch. It focuses exclusively on CME futures contracts including ES, NQ, YM, CL, GC, and other CME-listed products.\n\nLucid underwent a significant rules update in February-March 2026 that streamlined its account types and improved its Live transition process." },
      { id: "how-eval-works", heading: "How the evaluations work", body: "Lucid offers multiple paths to funded trading.\n\nLucidFlex is the standout: a one-phase evaluation with a 50% consistency rule (only during evaluation, removed once funded), no daily loss limit, and EOD trailing drawdown. Minimum 5 trading days to pass. Once funded, the consistency rule is completely removed. This means your best day can be 90% of your total profit without penalty.\n\nLucidPro is a faster path: 1-day minimum to pass, full contract size immediately, but a 35% consistency rule remains in the funded phase and there is a daily loss limit.\n\nLucidDirect skips evaluation entirely. You pay a higher one-time fee and start trading for payouts immediately. Stricter rules apply including a 20% consistency requirement.\n\nAll account types use end-of-day trailing drawdown set at 4% of the initial balance." },
      { id: "account-types", heading: "Account sizes and pricing", body: "All pricing is one-time with no recurring subscriptions.\n\nLucidFlex: approximately $175 for $50K, scaling up for $100K and $150K accounts.\n\nLucidPro: approximately $129.50 for $50K. The cheapest evaluation option at Lucid.\n\nLucidDirect (instant funded): higher one-time fee, no evaluation required.\n\nAccount sizes range from $25K to $150K. The $25K account is the cheapest entry point for traders on a tight budget.\n\nActivation fee is $50 for Pro accounts and $0 for Flex accounts. Both are lower than TopStep's $149.\n\nPlatform support includes Rithmic, Tradovate, NinjaTrader, and Quantower. Unlike TopStep, you have real platform choice." },
      { id: "fine-print", heading: "The fine print", body: "Lucid's rule set is one of the cleanest in the industry, but there are important details.\n\nNo overnight holding until you reach LucidLive (real capital). All positions must be closed intraday during evaluation and funded sim phases. This means swing trading is not available until you've progressed through multiple payout cycles.\n\nThe 5-second rule: at least 50% of your total profits must come from trades held longer than 5 seconds. This prevents pure latency arbitrage and HFT exploitation.\n\nPayout caps on Flex accounts range from $1,500 to $4,000 per cycle depending on the payout number. These caps are lower than some competitors and limit how quickly you can extract large profits.\n\nAfter 6 payouts (or earlier at risk team discretion), traders transition to LucidLive, which is real-capital trading. The LucidLive transition caps at $5,000 transfer per account regardless of how much you made in the sim phase. Any profits above $5,000 in the sim are forfeited during transition.\n\nLucidLive profit split was updated in March 2026 from 80/20 to 90/10.\n\nTraders must place at least one trade every 20 days to keep accounts active.\n\nNews trading is allowed on all accounts with no blackout periods." },
      { id: "payout-structure", heading: "Payout structure", body: "Payout speed is Lucid's standout feature. Average processing time is 15 minutes, with US ACH transfers arriving same-day in most cases. This is dramatically faster than TopStep (1-3 business days) and Apex (5 business days).\n\nProfit split: LucidFlex pays 90/10 throughout. LucidPro and LucidDirect pay 100% of the first $10,000, then 90/10.\n\nPayout frequency: LucidPro allows payouts every 3 days. LucidFlex payouts are per cycle.\n\nPayment methods include ACH, wire transfer, and PayPal.\n\nThe path to LucidLive (real capital) requires 6 payouts. This is a genuine transition to trading with the firm's actual money on live CME exchanges, not a simulation. However, the $5,000 transfer cap per account means you effectively start your live account with modest capital regardless of sim performance." },
    ],
    verdict: "Lucid Trading has the cleanest rule set and fastest payouts in the futures prop firm space. LucidFlex (no funded consistency, no DLL) is the most permissive funded structure available anywhere. The 15-minute payout processing is unmatched. The critical question is trust: Lucid launched in 2025, making it the newest firm in this comparison by a wide margin. The $5,000 LucidLive transfer cap and per-cycle payout limits on Flex are real constraints. If you're comfortable with a newer firm and value clean rules over a long track record, Lucid is compelling.",
    bestFor: "Traders who prioritize clean rules, fast payouts, and hate funded consistency requirements. Anyone who wants the most forgiving funded account structure.",
    avoidIf: "You value a long track record and established reputation. Or if you plan to swing trade (not available until Live phase). Or if you need to extract large payouts quickly (Flex caps are modest).",
    relatedTerms: [
      { term: "Drawdown", slug: "drawdown" },
      { term: "Prop Firm / Funded Account", slug: "prop-firm" },
      { term: "Mark to Market", slug: "mark-to-market" },
      { term: "Leverage", slug: "leverage" },
    ],
    specs: [
      { label: "Plan", values: ["Flex $50K", "Pro $50K", "Direct $50K"] },
      { label: "Cost (one-time)", values: ["~$175", "~$129.50", "Higher"] },
      { label: "Min. days", values: ["5", "1", "0 (instant)"] },
      { label: "Funded consistency", values: ["None", "35%", "20%"] },
      { label: "Daily loss limit", values: ["No", "Yes", "Yes"] },
      { label: "Activation fee", values: ["$0", "$50", "$0"] },
      { label: "Payout speed", values: ["~15 min", "~15 min", "~15 min"] },
    ],
    pros: [
      "15-minute average payout processing (fastest in industry)",
      "LucidFlex: no daily loss limit AND no funded consistency rule",
      "One-time fees, no monthly subscriptions",
      "Clean, minimal rule set compared to all competitors",
      "EOD drawdown on all account types",
      "Multiple platform options (Rithmic, Tradovate, NinjaTrader, Quantower)",
      "News trading allowed with no restrictions",
    ],
    cons: [
      "Newest firm in this comparison (launched 2025), shortest track record",
      "No overnight holding until LucidLive phase",
      "Payout caps per cycle on Flex ($1,500-$4,000) are relatively low",
      "LucidLive transition capped at $5,000 per account regardless of sim profits",
      "5-second trade holding rule may affect very fast scalpers",
      "Limited educational resources compared to TopStep",
    ],
  },
];

export function getFirmBySlug(slug) {
  return firmReviews.find(f => f.slug === slug);
}

export function getAdjacentFirms(slug) {
  const idx = firmReviews.findIndex(f => f.slug === slug);
  return {
    prev: idx > 0 ? firmReviews[idx - 1] : null,
    next: idx < firmReviews.length - 1 ? firmReviews[idx + 1] : null,
  };
}
